const ORDER_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  AGENT_LOCKED: "AGENT_LOCKED",
  AGENT_RESEARCHING: "AGENT_RESEARCHING",
  REPORT_SUBMITTED: "REPORT_SUBMITTED",
  WAITING_USER_REVIEW: "WAITING_USER_REVIEW",
  USER_REJECTED: "USER_REJECTED",
  WAITING_PAYMENT: "WAITING_PAYMENT",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  ORDER_PLACED: "ORDER_PLACED",
  CARGO_IN_TRANSIT: "CARGO_IN_TRANSIT",
  ARRIVED_AT_CARGO: "ARRIVED_AT_CARGO",
  COMPLETED: "COMPLETED",
  CANCELLED_BY_USER: "CANCELLED_BY_USER",
  CANCELLED_BY_ADMIN: "CANCELLED_BY_ADMIN",
  CANCELLED_NO_AGENT: "CANCELLED_NO_AGENT",
});

const ORDER_STATUS_FLOW = [
  ORDER_STATUS.DRAFT,
  ORDER_STATUS.PUBLISHED,
  ORDER_STATUS.AGENT_LOCKED,
  ORDER_STATUS.AGENT_RESEARCHING,
  ORDER_STATUS.REPORT_SUBMITTED,
  ORDER_STATUS.WAITING_USER_REVIEW,
  ORDER_STATUS.USER_REJECTED,
  ORDER_STATUS.WAITING_PAYMENT,
  ORDER_STATUS.PAYMENT_EXPIRED,
  ORDER_STATUS.PAYMENT_CONFIRMED,
  ORDER_STATUS.ORDER_PLACED,
  ORDER_STATUS.CARGO_IN_TRANSIT,
  ORDER_STATUS.ARRIVED_AT_CARGO,
  ORDER_STATUS.COMPLETED,
  ORDER_STATUS.CANCELLED_BY_USER,
  ORDER_STATUS.CANCELLED_BY_ADMIN,
  ORDER_STATUS.CANCELLED_NO_AGENT,
];

const ACTIVE_STATUSES = ORDER_STATUS_FLOW.filter(
  (status) =>
    ![
      ORDER_STATUS.COMPLETED,
      ORDER_STATUS.CANCELLED_BY_USER,
      ORDER_STATUS.CANCELLED_BY_ADMIN,
      ORDER_STATUS.CANCELLED_NO_AGENT,
      ORDER_STATUS.USER_REJECTED,
      ORDER_STATUS.PAYMENT_EXPIRED,
    ].includes(status)
);

const allowedTransitions = {
  user: {
    [ORDER_STATUS.DRAFT]: [ORDER_STATUS.PUBLISHED],
    [ORDER_STATUS.PUBLISHED]: [ORDER_STATUS.CANCELLED_BY_USER],
    [ORDER_STATUS.WAITING_USER_REVIEW]: [
      ORDER_STATUS.USER_REJECTED,
      ORDER_STATUS.WAITING_PAYMENT,
    ],
    [ORDER_STATUS.ARRIVED_AT_CARGO]: [ORDER_STATUS.COMPLETED],
  },
  agent: {
    [ORDER_STATUS.PUBLISHED]: [ORDER_STATUS.AGENT_LOCKED],
    [ORDER_STATUS.AGENT_LOCKED]: [ORDER_STATUS.AGENT_RESEARCHING],
    [ORDER_STATUS.AGENT_RESEARCHING]: [ORDER_STATUS.REPORT_SUBMITTED],
    [ORDER_STATUS.PAYMENT_CONFIRMED]: [ORDER_STATUS.ORDER_PLACED],
    [ORDER_STATUS.ORDER_PLACED]: [ORDER_STATUS.CARGO_IN_TRANSIT],
    [ORDER_STATUS.CARGO_IN_TRANSIT]: [ORDER_STATUS.ARRIVED_AT_CARGO],
  },
  admin: {
    [ORDER_STATUS.WAITING_PAYMENT]: [ORDER_STATUS.PAYMENT_CONFIRMED],
    [ORDER_STATUS.PUBLISHED]: [ORDER_STATUS.CANCELLED_NO_AGENT],
    ANY_ACTIVE: [ORDER_STATUS.CANCELLED_BY_ADMIN],
  },
  system: {
    [ORDER_STATUS.REPORT_SUBMITTED]: [ORDER_STATUS.WAITING_USER_REVIEW],
  },
};

function canTransition(from, to, actorRole = "system") {
  const map = allowedTransitions[actorRole] || {};
  const allowedList = map[from] || [];

  if (allowedList.includes(to)) return true;

  // Admin can cancel from any active status
  if (
    actorRole === "admin" &&
    map.ANY_ACTIVE &&
    map.ANY_ACTIVE.includes(to) &&
    ACTIVE_STATUSES.includes(from)
  ) {
    return true;
  }

  return false;
}

module.exports = {
  ORDER_STATUS,
  ORDER_STATUS_FLOW,
  ACTIVE_STATUSES,
  canTransition,
};
